'use client' 
import type { Metadata } from "next";
import { montserrat } from "../components/Fonts/Fonts";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
// import { NextUIProvider } from '@nextui-org/react';
import Footer from "../components/Footer/Footer";
import NavBar from "../components/Navbar/NavBar";
// import Background from "../components/Background/Background";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
{

  return (
    <html lang="en">
      <head>
      <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
        />
      </head>
      <body className={`body ${montserrat.className} antialiased`}>
      {/* <NextUIProvider> */}
        <NavBar/>
        {children}
        <Footer />
      {/* </NextUIProvider> */}
      </body>
    </html>
  );
}
