'use client' 
import type { Metadata } from "next";
import { montserrat } from "../components/Fonts/Fonts";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import Footer from "../components/Footer/Footer";
import NavBar from "../components/Navbar/NavBar";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
{

  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <NavBar/>
        {/* <img src="/img/background.svg"/> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
